### ISSUE TITLE
Multiples git repo for multiple docs

### ISSUE THREAD

**Issue by nothing-fr** [codex-project/legacy-codex#32]
Is it possible to clone multiples git repo in /public/docs ?

When i have multiples git repo, it's not working, i've always this error (but with only one, it works) : 

` fatal: Not a git repository (or any of the parent directories): .git `

**Comment by kaidesu** [comment]
Certainly, as long as they're in their own directories.

```
cd docs/
git clone git@github.com:example/repo1.git
git clone git@github.com:example/repo2.git
```

Should result in having:

```
docs/
    repo1/
    repo2/
```

**Comment by nothing-fr** [comment]
it's not working for me, i'm using the master branch.
I don't understand why...

**Comment by kaidesu** [comment]
Have you experienced this issue in the tagged `1.1.0` release?

**Comment by nothing-fr** [comment]
ok, it's now working. I had to give a default manual to make it work.
If i don't specify it, I have the error message...

**Comment by nothing-fr** [comment]
aside of this problem, is it possible to use images in the markdown (not external images) ?

**Comment by kaidesu** [comment]
Of course - you're able to reference images locally as you would with HTML `<img>` tags.

```md
![Alt Text](/path/to/image.png)
```
